// Allocation maths. A port of scripts/allocate.py, which is itself the
// display-side twin of data/wimtm_data/apportion.py — three implementations of
// one algorithm, which is unavoidable: the split depends on the figure the reader
// types, so it cannot be precomputed and shipped. `tests/apportion.test.js` checks
// this one against fixtures generated by the Python, because three copies
// agreeing by inspection is not evidence.
//
// Everything works in **whole rupees**, which is also the precision the UI shows.
// That is deliberate: if allocation ran in paise and the display truncated, a
// parent of ₹20,330.96 would sit above children reading ₹7,504 + ₹4,120 + … =
// ₹20,328, and the subtotals would visibly fail to add up. Apportioning at
// display precision makes what you see the thing that is conserved.
//
// A leaf showing ₹0 therefore means "less than a rupee of your tax", which is
// honest rather than hidden. With 56 ministries on screen this is common, and it
// is the intended reading.

/**
 * Split `total` across `weights` so the parts sum to `total` exactly.
 *
 * Rounding each share independently leaves the parts a few rupees short of the
 * total. Largest-remainder hands the leftover to the parts with the biggest
 * fractional claim, so nothing is invented or lost. Ties break by index, which
 * keeps the result reproducible.
 *
 * **This runs in BigInt and that is not optional.** The intermediate
 * `total * weight` is computed before dividing, and these are national budget
 * figures: the largest weight in the dataset is ₹4.96e13, so the product reaches
 * ~2.5e27 — past `Number.MAX_SAFE_INTEGER` (9.007e15) by eleven orders of
 * magnitude. In `Number` arithmetic that silently produces wrong money. The
 * individual amounts are well inside the safe range, so BigInt stays inside this
 * function and callers only ever see `number`.
 */
export function apportion(total: number, weights: number[]): number[] {
  if (!Number.isInteger(total) || total < 0) {
    throw new Error(`apportion: total must be a non-negative integer, got ${total}`);
  }
  if (weights.some((w) => !Number.isInteger(w) || w < 0)) {
    // Guarded rather than assumed: BigInt division truncates toward zero where
    // Python's `//` floors. They agree only for non-negative operands, and this
    // port has to match the Python exactly.
    throw new Error("apportion: weights must be non-negative integers");
  }

  const big = weights.map(BigInt);
  const weightSum = big.reduce((a, b) => a + b, 0n);
  if (weightSum <= 0n) {
    throw new Error("cannot apportion across weights that sum to zero");
  }

  const totalBig = BigInt(total);
  const amounts = big.map((w) => (totalBig * w) / weightSum);
  const leftover = Number(totalBig - amounts.reduce((a, b) => a + b, 0n));

  const order = big
    .map((w, index) => ({ index, remainder: (totalBig * w) % weightSum }))
    .sort((a, b) => {
      if (a.remainder === b.remainder) return a.index - b.index;
      return a.remainder > b.remainder ? -1 : 1;
    });

  for (let i = 0; i < leftover; i += 1) {
    amounts[order[i].index] += 1n;
  }

  return amounts.map(Number);
}

/**
 * Round half to even — Python's `round()`, not JavaScript's `Math.round()`.
 *
 * This is not a stylistic choice. `Math.round(20.5)` is 21; Python's
 * `round(20.5)` is 20, because it breaks ties toward the even neighbour. The
 * dataset pipeline and scripts/allocate.py are the reference implementations
 * and both are Python, so a JS port using `Math.round` disagrees with them on
 * every exact half — which is reachable with ordinary inputs: ₹57 paid at a 10%
 * surcharge gives a base of ₹50, and 41% of that is exactly 20.5.
 *
 * The golden fixtures caught this; nothing about the code looked wrong.
 */
export function roundHalfEven(value: number): number {
  const floor = Math.floor(value);
  const fraction = value - floor;
  if (fraction > 0.5) return floor + 1;
  if (fraction < 0.5) return floor;
  return floor % 2 === 0 ? floor : floor + 1;
}

/** A node of the view model emitted by scripts/build-data.mjs. */
export interface Row {
  id: string;
  label: string;
  amountRupees: number;
  tone: string | null;
  desc?: string;
  spentOn?: string;
  url?: string;
  children: Row[];
}

/** The same node with the reader's own money attached. */
export interface Allocated extends Row {
  /** This reader's share, in whole rupees. */
  yours: number;
  children: Allocated[];
}

/**
 * Allocate `total` down a tree, one level at a time.
 *
 * Computing each node independently as `total * node / root` would let siblings
 * miss their parent by a rupee or two. Apportioning at each level instead makes
 * "children sum to parent" true by construction, at every depth.
 */
export function allocateRows(rows: Row[], total: number): Allocated[] {
  if (rows.length === 0) return [];

  const weights = rows.map((row) => row.amountRupees);
  const sum = weights.reduce((a, b) => a + b, 0);

  // A branch of entirely zero-valued children: nothing to split, and apportion
  // would rightly refuse. Every part is zero, which is the truthful answer.
  const parts = sum <= 0 ? rows.map(() => 0) : apportion(total, weights);

  return rows.map((row, index) => ({
    ...row,
    yours: parts[index],
    children: allocateRows(row.children, parts[index]),
  }));
}

// --- how an individual's tax payment is actually composed ---------------------
//
// A rupee of income tax is not one thing. Parliament levies a base tax, then a
// surcharge on high incomes, then a cess on top of both. Only the base tax enters
// the divisible pool that states get a share of — cess and surcharge are the
// Union's alone.
//
// That is the whole reason the headline "41% goes to states" overstates what
// states receive, and the reason this split is worth showing a taxpayer.

/** 4% on tax plus surcharge, levied on everyone. */
export const HEALTH_EDUCATION_CESS = 0.04;

/**
 * Surcharge rates for individuals. Which one applies depends on total income,
 * not on the tax paid, so the reader has to tell us.
 */
export const SURCHARGE_RATES = [
  { value: 0, label: "None" },
  { value: 0.1, label: "10%" },
  { value: 0.15, label: "15%" },
  { value: 0.25, label: "25%" },
  { value: 0.37, label: "37%" },
] as const;

export interface Parts {
  base: number;
  surcharge: number;
  cess: number;
}

/**
 * Split what someone paid back into base tax, surcharge and cess.
 *
 * Working backwards from the total, because that is the number a taxpayer
 * actually knows:
 *
 *     total = base x (1 + surcharge) x (1 + cess)
 *
 * Rounding is arranged so the three parts always add back to exactly what was
 * entered — cess absorbs the remainder rather than the display quietly losing
 * a rupee.
 */
export function decompose(totalPaid: number, surchargeRate: number): Parts {
  const divisor = (1 + surchargeRate) * (1 + HEALTH_EDUCATION_CESS);
  const base = roundHalfEven(totalPaid / divisor);
  const surcharge = roundHalfEven(base * surchargeRate);
  return { base, surcharge, cess: totalPaid - base - surcharge };
}

export interface Route extends Parts {
  toStates: number;
  toCess: number;
  toUnion: number;
  /** What actually reached the state, as a percentage of what was paid. */
  effectiveStatePercent: number;
}

/**
 * Trace where a taxpayer's money goes, in whole rupees that add up.
 *
 * Three destinations, because the three parts of a tax bill are governed
 * differently:
 *
 * - **base tax** is shareable. The states take the Finance Commission's
 *   percentage; the rest funds the Union's general spending.
 * - **surcharge** is ordinary Union money that simply is not shared.
 * - **cess** is neither. It is levied for a stated purpose and credited to
 *   reserve funds that may finance only their own schemes.
 *
 * `toStates + toCess + toUnion` is exactly what was paid.
 *
 * Note there is no second discount on the way to the states. The comp applied a
 * `1/1.1` "pool factor" on top of the 41%, but the divisible pool is gross tax
 * *minus cess and surcharge*, and those are already removed here — so base tax is
 * the reader's share of the pool, and the award percentage applies to it directly.
 */
export function route(
  totalPaid: number,
  surchargeRate: number,
  statesSharePercent: number
): Route {
  const parts = decompose(totalPaid, surchargeRate);
  const toStates = roundHalfEven((parts.base * statesSharePercent) / 100);
  const unionFromBase = parts.base - toStates;

  return {
    ...parts,
    toStates,
    toCess: parts.cess,
    toUnion: unionFromBase + parts.surcharge,
    effectiveStatePercent: totalPaid ? (100 * toStates) / totalPaid : 0,
  };
}
