// The TS allocation maths against fixtures generated by the Python.
//
// This exists because the algorithm now lives in three places
// (data/wimtm_data/apportion.py, scripts/allocate.py, src/lib/allocate.ts) and
// cannot be reduced to one: the split depends on the figure a reader types, so it
// is computed in the browser. Regenerate with `npm run fixtures`.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { apportion, allocateRows, decompose, route, type Row } from "../src/lib/allocate.ts";
import { groupIndian, formatInr } from "../src/lib/format.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const fixtures = JSON.parse(readFileSync(join(HERE, "fixtures.json"), "utf8"));

test("apportion matches the Python, case for case", () => {
  for (const testCase of fixtures.apportion) {
    assert.deepEqual(
      apportion(testCase.total, testCase.weights),
      testCase.expected,
      `apportion disagreed with the Python: ${testCase.why}`
    );
  }
});

test("apportion conserves the total exactly", () => {
  for (const testCase of fixtures.apportion) {
    const parts = apportion(testCase.total, testCase.weights);
    const sum = parts.reduce((a, b) => a + b, 0);
    assert.equal(sum, testCase.total, `parts did not sum to the total: ${testCase.why}`);
  }
});

test("apportion survives national magnitudes that overflow Number", () => {
  // The reason this function runs in BigInt. `total * weight` is computed before
  // dividing, so with national figures on both sides the product reaches ~2.5e27
  // — past Number.MAX_SAFE_INTEGER (9.007e15) by eleven orders of magnitude.
  //
  // Worth being precise about when this actually bites, because it is narrower
  // than it sounds: for the amounts a reader types (₹57 to ₹47 lakh) a naive
  // Number implementation agrees with this one on every fixture. It diverges when
  // the *total* is itself a national figure — allocating the whole union budget
  // across all 56 ministries drifts by ₹10. That path is real (the build-time
  // reconciliation walks it), and an implementation that is right only for small
  // inputs is not right.
  const wholeBudget = fixtures.apportion.find((c: { why: string }) =>
    c.why.startsWith("whole union budget")
  );
  assert.ok(wholeBudget, "fixture for the whole-budget case is missing");

  const parts = apportion(wholeBudget.total, wholeBudget.weights);
  assert.deepEqual(parts, wholeBudget.expected);
  assert.equal(
    parts.reduce((a: number, b: number) => a + b, 0),
    wholeBudget.total
  );

  // The same algorithm in Number arithmetic, to show the divergence is real
  // rather than theoretical.
  const naive = (total: number, weights: number[]) => {
    const sum = weights.reduce((a, b) => a + b, 0);
    const amounts = weights.map((w) => Math.floor((total * w) / sum));
    const leftover = total - amounts.reduce((a, b) => a + b, 0);
    const order = weights
      .map((w, i) => ({ i, rem: (total * w) % sum }))
      .sort((a, b) => b.rem - a.rem || a.i - b.i);
    for (let k = 0; k < leftover; k += 1) amounts[order[k].i] += 1;
    return amounts;
  };

  const drift = naive(wholeBudget.total, wholeBudget.weights).reduce(
    (acc: number, value: number, i: number) => acc + Math.abs(value - wholeBudget.expected[i]),
    0
  );
  assert.ok(drift > 0, "Number arithmetic should misallocate here — that is why BigInt is used");
});

test("apportion refuses inputs whose semantics would diverge from the Python", () => {
  assert.throws(() => apportion(100, [0, 0]), /sum to zero/);
  assert.throws(() => apportion(100, [-1, 2]), /non-negative/);
  assert.throws(() => apportion(-1, [1, 2]), /non-negative/);
  assert.throws(() => apportion(1.5, [1, 2]), /integer/);
});

test("decompose and route match the Python across every surcharge band", () => {
  for (const testCase of fixtures.tax) {
    const parts = decompose(testCase.paid, testCase.surcharge);
    assert.equal(parts.base, testCase.decompose.base);
    assert.equal(parts.surcharge, testCase.decompose.surcharge);
    assert.equal(parts.cess, testCase.decompose.cess);

    const routed = route(testCase.paid, testCase.surcharge, 41);
    assert.equal(routed.toStates, testCase.route.to_states);
    assert.equal(routed.toCess, testCase.route.to_cess);
    assert.equal(routed.toUnion, testCase.route.to_union);
  }
});

test("the three parts of a tax bill add back to what was paid", () => {
  for (const testCase of fixtures.tax) {
    const { base, surcharge, cess } = decompose(testCase.paid, testCase.surcharge);
    assert.equal(base + surcharge + cess, testCase.paid);

    const routed = route(testCase.paid, testCase.surcharge, 41);
    assert.equal(
      routed.toStates + routed.toCess + routed.toUnion,
      testCase.paid,
      "state share + cess + union must be exactly what was paid"
    );
  }
});

test("allocateRows conserves money at every depth", () => {
  const tree: Row[] = [
    {
      id: "a",
      label: "A",
      amountRupees: 7,
      tone: null,
      children: [
        { id: "a1", label: "A1", amountRupees: 5, tone: null, children: [] },
        { id: "a2", label: "A2", amountRupees: 2, tone: null, children: [] },
      ],
    },
    { id: "b", label: "B", amountRupees: 3, tone: null, children: [] },
  ];

  const allocated = allocateRows(tree, 1_000_001);
  assert.equal(allocated[0].yours + allocated[1].yours, 1_000_001);
  assert.equal(
    allocated[0].children[0].yours + allocated[0].children[1].yours,
    allocated[0].yours,
    "children must sum to their parent, not to an independently rounded figure"
  );
});

test("allocateRows gives zero rather than throwing on an all-zero branch", () => {
  const rows: Row[] = [
    { id: "x", label: "X", amountRupees: 0, tone: null, children: [] },
    { id: "y", label: "Y", amountRupees: 0, tone: null, children: [] },
  ];
  assert.deepEqual(
    allocateRows(rows, 500).map((r) => r.yours),
    [0, 0]
  );
});

test("digits group the Indian way, not the Western one", () => {
  assert.equal(groupIndian("1286885"), "12,86,885");
  assert.equal(groupIndian("100"), "100");
  assert.equal(groupIndian("1000"), "1,000");
  assert.equal(formatInr(120000), "₹1,20,000");
  assert.equal(formatInr(0), "₹0");
});
